# .streamlit/config.toml

[theme]
primaryColor = "#28a745"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = false

[global]
# Désactive le mode développement pour autoriser le changement de port
developmentMode = false

[server]
# Port sur lequel servira l'app
port = 3000

# Protection contre les attaques CSRF
enableXsrfProtection = true

# CORS activé si vous avez besoin d’appels cross-origin ;
# sinon laissez commenté (valeur par défaut = false).
# enableCORS = true
